[build-system]
requires = [
    "setuptools",
    "wheel",
    "scikit-build @ git+https://github.com/henryiii/scikit-build@henryiii/fix/logger",
    "ninja",
    "cmake>=3.16",
    "pybind11>=2.9.1",
]
